apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_NAME: {{ .Values.backend.config.DB_NAME }}
  DB_USER: {{ .Values.backend.config.DB_USER }}
  DB_PASSWORD: {{ .Values.backend.config.DB_PASSWORD }}
  DB_HOST: {{ .Values.backend.config.DB_HOST }}

