apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: frontend
